#ifndef MPU_REGS_H_
#define MPU_REGS_H_

#include <stdint.h>

#define MPU_ADDR 0x68

#define MPU_CONFIG_ADDR              0x1A
#define MPU_CONFIG_EXT_SYNC_SET_BMSK 0x38
#define MPU_CONFIG_EXT_SYNC_SET_SHFT 0x02
#define MPU_CONFIG_DLPF_CFG_BMSK     0x07
#define MPU_CONFIG_DLPF_CFG_SHFT     0x00

#define MPU_GYRO_CONFIG_ADDR         0x1B
#define MPU_GYRO_CONFIG_FS_SEL_BMSK  0x18
#define MPU_GYRO_CONFIG_FS_SEL_SHFT  0x03

#define MPU_ACCEL_CONFIG_ADDR          0x1C
#define MPU_ACCEL_CONFIG_AFS_SEL_BMSK  0x18
#define MPU_ACCEL_CONFIG_AFS_SEL_SHFT  0x03

#define MPU_PWR_MGMT_1_ADDR       0x6B
#define MPU_PWR_MGMT_1_RESET_BMSK 0x80
#define MPU_PWR_MGMT_1_RESET_SHFT 0x07
#define MPU_PWR_MGMT_1_CYCLE_BMSK 0x20
#define MPU_PWR_MGMT_1_CYCLE_SHFT 0x05
#define MPU_PWR_MGMT_1_TEMP_DIS_SHFT 0x3
#define MPU_PWR_MGMT_1_CLKSEL_SHFT 0x00

#define MPU_PWR_MGMT_2_ADDR       0x6C
#define MPU_PWR_MGMT_2_LP_WAKE_CTRL_SHFT 0x6
#define MPU_PWR_MGMT_2_STBY_ZG_SHFT 0x0
#define MPU_PWR_MGMT_2_STBY_YG_SHFT 0x1
#define MPU_PWR_MGMT_2_STBY_XG_SHFT 0x2

#define MPU_ACCEL_XOUT_ADDR 0x3B
#define MPU_TEMP_OUT_ADDR 0x41
#define MPU_GYRO_XOUT_ADDR 0x43

#define MPU_INT_ENABLE_ADDR 0x38
#define MPU_INT_ENABLE_DATA_RDY_EN_SHFT 0x0

#define MPU_INT_PIN_CFG_ADDR 0x37
#define MPU_INT_PIN_CFG_INT_LEVEL_SHFT 0x7
#define MPU_INT_PIN_CFG_INT_OPEN_SHFT 0x6
#define MPU_INT_PIN_CFG_LATCH_INT_EN_SHFT 0x5
#define MPU_INT_PIN_CFG_INT_RD_CLEAR_SHFT 0x4
#define MPU_INT_PIN_CFG_FSYNC_INT_LEVEL_SHFT 0x3
#define MPU_INT_PIN_CFG_FSYNC_INT_EN_SHFT 0x2
#define MPU_INT_PIN_CFG_I2C_BYPASS_EN_SHFT 0x1

#define MPU_INT_STATUS_ADDR 0x3A


#define MPU_WHO_AM_I_ADDR 0x75

//#define MPU_WHO_AM_I_POR 0x71  // MPU 9000
#define MPU_WHO_AM_I_POR 0x68    // MPU 6000

#endif /* MPU_REGS_H_ */
